### ISSUE TITLE
'Refresh' button tooltip does not get translated for GVT (ng directive)

### ISSUE THREAD

**Issue by eoinjoyc** [bigfix/adf#1]
GVT team raised a defect for our product due to the refresh button tooltip not getting translated. This is caused by the angular top-navigation directive not using the resources.js localization file for the 'Refresh' tooltip.

It's a quick fix. Create a scope variable in the directive, and assign it the pre-existing "temui.l10n.refresh" value from resources.js. Then assign the scope variable to the button's "title" value.

I can check in the fix, if needed.

**Comment by briangreenery** [comment]
I don't think there's any active maintainer of the ADF. Do you want to take over ownership of this repository so that you can make the changes that you need?

**Comment by eoinjoyc** [comment]
I can't say how actively I'll be using the ADF after our product releases, but I'd be happy to maintain it for the time being

**Comment by briangreenery** [comment]
I just made you an admin on this project.
